### ISSUE TITLE
Planets and Humans

### ISSUE THREAD

**Issue by jooovel** [jooovel/love2d-stuff#9]
- Create a Planet class that holds inhabitants, refilling stations and smuggle destinations
- Create a Human class, because we need someone driving the ships
- Create a Galaxy class where planets and smuggling routes can exist

- Create a Game-state machine

**Comment by Avicted** [comment]
Hump for Game-state? http://hump.readthedocs.io/en/latest/index.html

**Comment by Avicted** [comment]
Planet + Galaxy classes merged.
